version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51KBJaMLOM5jBHloonKg32SwP01RutBbGxGSO4aYlSDozE1jh8eNSiISY1VRuOB2MNuBHvLDqUkIvHYgXmrtLKwYc00j79pXF6N
      - STRIPE_TEST_SECRET_KEY=sk_test_51KBJaMLOM5jBHlooauzfk2vY4VsXGK74cJQGIdBznYUA4l5R5wg1CMItOGKoU4eTIjGffSMp0Xx45kHGB3fjY3b000vdDwb985
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
