# Generated by Django 3.1 on 2021-12-26 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('UDF', 'Undefined'), ('AC', 'Action'), ('AC-ADV', 'Action-adventure'), ('ADV', ' Adventure'), ('RP', 'Role-playing'), ('SM', 'Simulation'), ('STR', 'Strategy'), ('SPO', 'Sports'), ('MMO', 'MMO'), ('SB', 'Sandbox')], default='UDF', max_length=6)),
                ('platforms', models.CharField(choices=[('Windows', 'Windows'), ('Android', 'Android'), ('Xbox', 'Xbox'), ('PS', 'Playstation'), ('Nintendo', 'Nintendo')], default='Windows', max_length=8)),
                ('producents', models.CharField(max_length=64)),
                ('publishers', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
