# Generated by Django 3.1.14 on 2022-01-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('Undefined', 'Undefined'), ('Action', 'Action'), ('Action-adventure', 'Action-adventure'), ('Adventure', ' Adventure'), ('Role-playing', 'Role-playing'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('MMO', 'MMO'), ('Sandbox', 'Sandbox')], default='Undefined', max_length=16)),
                ('platforms', models.CharField(choices=[('Windows', 'Windows'), ('Android', 'Android'), ('Xbox', 'Xbox'), ('PS', 'Playstation'), ('Nintendo', 'Nintendo')], default='Windows', max_length=8)),
                ('producents', models.CharField(max_length=64)),
                ('publishers', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'permissions': [('special_status', 'Can play all games')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game')),
            ],
        ),
    ]
